const RecipeActionTypes = {
  CATEGORIES_LIST:"CATEGORIES_LIST",
  GET_CATEGORIES_LIST:"GET_CATEGORIES_LIST",
  GET_CATEGORIES_LIST_SUCCESS:"GET_CATEGORIES_LIST_SUCCESS",
  GET_CATEGORIES_LIST_FAILURE:"GET_CATEGORIES_LIST_FAILURE"


  
};

export default RecipeActionTypes;
