const MemberActionTypes = {
  ADD_FAMILY_MEMBER: "ADD_FAMILY_MEMBER",
  REMOVE_FAMILY_MEMBER:"REMOVE_FAMILY_MEMBER",
  GET_MEMBER_LIST:"GET_MEMBER_LIST",
  GET_MEMBER_LIST_SUCCESS:"GET_MEMBER_LIST_SUCCESS",
  GET_MEMBER_LIST_FAILURE:"GET_MEMBER_LIST_FAILURE",
  MEMBER_ADDED_SUCCESS:"MEMBER_ADDED_SUCCESS",
  MEMBER_ADDED_FAILURE:"MEMBER_ADDED_FAILURE",
  MEMBER_REMOVED_SUCCESS:"MEMBER_REMOVED_SUCCESS",
  MEMBER_REMOVED_FAILURE:"MEMBER_REMOVED_FAILURE"
  
};

export default MemberActionTypes;
